apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp-golden-path
  description: Backstage ベースの Internal Developer Platform（このリポジトリ自身）
  annotations:
    github.com/project-slug: kmryst/idp-golden-path
spec:
  type: website
  owner: platform
  lifecycle: experimental
  system: kmryst-portfolio
